### ISSUE TITLE
[URGENT] Lacking many currencies suddenly

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [Formicka/exchangerate.host#209] opened 2023-03-13 08:02 UTC
Today's result has much smaller number of currencies (71) than yesterday (169). Maybe affecting many services. 

What's happened? Are you well?

YESTERDAY  https://api.exchangerate.host/2023-03-12

{"motd":{"msg":"If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.","url":"https://exchangerate.host/#/donate"},"success":true,"historical":true,"base":"EUR","date":"2023-03-12","rates":{"AED":3.925831,"AFN":94.519191,"ALL":114.653457,"AMD":412.947736,"ANG":1.917597,"AOA":541.194781,"ARS":212.014569,"AUD":1.612392,"AWG":1.927074,"AZN":1.816804,"BAM":1.965173,"BBD":2.137848,"BDT":112.111265,"BGN":1.963385,"BHD":0.403534,"BIF":2213.109351,"BMD":1.069001,"BND":1.441333,"BOB":7.349498,"BRL":5.576218,"BSD":1.068677,"BTC":0.000049,"BTN":87.223572,"BWP":14.143456,"BYN":2.684852,"BZD":2.144231,"CAD":1.47384,"CDF":2204.690384,"CHF":0.980934,"CLF":0.031436,"CLP":851.081476,"CNH":7.391623,"CNY":7.381007,"COP":5022.146047,"CRC":583.000723,"CUC":1.068549,"CUP":27.520689,"CVE":110.807,"CZK":23.633987,"DJF":189.547168,"DKK":7.439016,"DOP":58.701477,"DZD":145.992721,"EGP":32.698084,"ERN":16.030886,"ETB":57.266917,"EUR":1,"FJD":2.392907,"FKP":0.885061,"GBP":0.884903,"GEL":2.757762,"GGP":0.885313,"GHS":13.148188,"GIP":0.885195,"GMD":65.460844,"GNF":9211.255288,"GTQ":8.307022,"GYD":224.402416,"HKD":8.388854,"HNL":26.257866,"HRK":7.530117,"HTG":163.210409,"HUF":382.518765,"IDR":16568.631628,"ILS":3.83254,"IMP":0.884803,"INR":87.621008,"IQD":1553.791839,"IRR":45180.662976,"ISK":150.713232,"JEP":0.885229,"JMD":162.68813,"JOD":0.759264,"JPY":143.673998,"KES":137.452421,"KGS":93.428397,"KHR":4307.355954,"KMF":493.593854,"KPW":961.860073,"KRW":1411.410248,"KWD":0.32789,"KYD":0.887157,"KZT":480.812056,"LAK":17981.063654,"LBP":16035.57402,"LKR":345.662492,"LRD":171.53215,"LSL":19.500332,"LYD":5.166036,"MAD":11.063829,"MDL":19.971155,"MGA":4583.873789,"MKD":61.88677,"MMK":2233.375632,"MNT":3641.134803,"MOP":8.599723,"MRU":36.811426,"MUR":50.290077,"MVR":16.416002,"MWK":1086.325755,"MXN":19.660888,"MYR":4.830868,"MZN":68.292648,"NAD":19.617943,"NGN":490.749487,"NIO":38.931024,"NOK":11.308693,"NPR":139.557314,"NZD":1.735244,"OMR":0.412584,"PAB":1.069166,"PEN":4.028342,"PGK":3.752715,"PHP":58.972502,"PKR":298.75315,"PLN":4.678263,"PYG":7655.767778,"QAR":3.893077,"RON":4.914868,"RSD":117.705636,"RUB":81.446768,"RWF":1163.505706,"SAR":4.012971,"SBD":8.76306,"SCR":13.934588,"SDG":634.826834,"SEK":11.354617,"SGD":1.440935,"SHP":0.884804,"SLL":18879.159038,"SOS":606.213479,"SRD":36.847541,"SSP":139.212994,"STD":24392.739008,"STN":24.740145,"SVC":9.306632,"SYP":2685.222748,"SZL":19.492822,"THB":37.017911,"TJS":10.70151,"TMT":3.752086,"TND":3.337279,"TOP":2.532367,"TRY":20.275187,"TTD":7.228614,"TWD":32.964131,"TZS":2491.240961,"UAH":39.25346,"UGX":3952.938808,"USD":1.068511,"UYU":41.758806,"UZS":12128.881649,"VES":25.761867,"VND":25301.443373,"VUV":126.158614,"WST":2.883419,"XAF":655.489879,"XAG":0.052321,"XAU":0.001164,"XCD":2.888247,"XDR":0.800165,"XOF":655.489328,"XPD":0.001877,"XPF":119.24722,"XPT":0.00131,"YER":267.53014,"ZAR":19.545746,"ZMW":21.483616,"ZWL":344.132515}}

TODAY   https://api.exchangerate.host/2023-03-13

{"motd":{"msg":"If you or your company use this project or like what we doing, please consider backing us so we can continue maintaining and evolving this project.","url":"https://exchangerate.host/#/donate"},"success":true,"historical":true,"base":"EUR","date":"2023-03-13","rates":{"ARS":212.030647,"AUD":1.607892,"BBD":2.143484,"BMD":1.072767,"BRL":5.592009,"BSD":1.072698,"BTC":0.000048,"CAD":1.471795,"CHF":0.982441,"CNH":7.37641,"CNY":7.376701,"COP":5022.729021,"CUC":1.072443,"CUP":27.599767,"CZK":23.603859,"DKK":7.439198,"EGP":32.869161,"ERN":16.077577,"EUR":1,"FKP":0.885152,"GBP":0.884707,"GGP":0.885034,"GIP":0.884747,"HKD":8.409942,"HRK":7.532343,"HUF":381.737115,"IDR":16478.926389,"ILS":3.824225,"IMP":0.884436,"INR":87.795536,"JEP":0.885149,"JPY":143.660984,"KPW":964.61563,"KRW":1395.232912,"MNT":3651.567207,"MUR":50.535542,"MXN":19.61095,"MYR":4.804581,"NOK":11.266271,"NZD":1.73017,"PAB":1.072407,"PHP":58.813481,"PLN":4.667508,"RON":4.914635,"RUB":81.360668,"SEK":11.358225,"SGD":1.441822,"SHP":0.884762,"SLL":18933.253789,"SSP":139.612191,"STD":24462.632578,"SYP":2692.916182,"THB":37.053341,"TJS":10.732843,"TOP":2.539773,"TRY":20.327971,"TWD":32.761841,"TZS":2489.361743,"USD":1.073097,"VND":25245.438318,"VUV":126.519746,"WST":2.892103,"XAF":655.434271,"XAG":0.052651,"XAU":0.001699,"XOF":655.434931,"XPD":0.001704,"XPF":119.237097,"XPT":0.001325,"ZAR":19.507639,"ZWL":345.117753}}

**Comment by Andreychik32** [comment] 2023-03-13 09:59
I have the same problem.

**Comment by maysaleba** [comment] 2023-03-13 11:08
same for me. :(

**Comment by Sadicko** [comment] 2023-03-13 11:08
Having same issue. The currencies I mostly use are no longer found. GHS, AED, NGN etc and it is affecting the application

**Comment by alexmicic** [comment] 2023-03-13 11:49
Same here. Maybe @arzzen can check what is going on?

**Comment by BTJason** [comment] 2023-03-13 13:11
Having the same issue.  The CLP is the only one missing for my needs.

**Comment by maxtheaxe** [comment] 2023-03-13 13:21
Same. Can't see exchange rates for KZT, UAH, and a handful of others.

**Comment by arzzen** [comment] 2023-03-13 13:55
I have identified the cause of this incident and am actively working on a solution. I will update this post with more details. 
We apologise for any inconvenience caused.

**Comment by maxtheaxe** [comment] 2023-03-13 14:13
No worries, we all appreciate your hard work!

**Comment by arzzen** [comment] 2023-03-13 14:38
Good news! 

A fix has been implemented. All rates that were unavailable are now available again in the API response. 

Be adviced API requests are cached by default, for refresh data you can try to add an additional parameter `&v=` (or different) in the query (please do not flood API, if it's not necessary ;).

**Comment by BTJason** [comment] 2023-03-13 14:44
Thank you very much

**Closed** 2023-03-13 17:28 UTC
Labels: investigate

**Comment by HIRANO-Satoshi** [comment] 2023-03-13 22:02
@arzzen Thank you very much!!  My service has been recovered.

[https://luncho-index.org/countries](https://luncho-index.org/countries
)

I don't understand about the &v= parameter. Do you mean the API returns the latest rates if with ?v=, and cached rates if without ?v=?   What do you mean with 'or different'?

`https://api.exchangerate.host/latest?v=
`

I fetch data once a day and cache it. So, do I need to fetch new data with the ?v= option?

Where is doc for the v option?
